# Key settings (must edit)
project_title: Python basics
project_repo: lucydot/ChooChoo-2024
admins:
- lucydot
instructors:
- lucydot
students:
- 
web_address: https://lucydot.github.io/ChooChoo-2024

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true



